apiVersion: v1
kind: Service
metadata:
  name: appointment-directory-lb-service
  namespace: app-poc
  labels:
    app: appointment-directory-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: appointment-directory-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
