apiVersion: "v1"
kind: "Service"
metadata:
  name: "appointment-directory-app-service"
  namespace: "app-poc"
  labels:
    app: "appointment-directory-app"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "appointment-directory-app"
  type: "LoadBalancer"
  loadBalancerIP: ""
